language: node_js
node_js:
  - 'node'
  - '12'
  - '10'
  - '8'
before_script:
  - npm install -g istanbul codecov
script: npm run lint && istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
