# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_call:

jobs:
  continuous-integration:
    name: Lint and Test on NodeJS ${{matrix.node-version}}

    runs-on: ubuntu-latest

    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
          - 18
          - 20

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
      - run: npm i -g nyc
      - run: npm ci
      - run: npm run lint && nyc --reporter=json npm test
      - run: ./codecov -t ${CODECOV_TOKEN}
